server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust : smtp.gmail.com
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 335452151589-5o0utfsmjb093rpsjq9e8tf03879k8qr.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile   
            
          kakao:
            client-id: 4f4bbf221fa9e166125266403c90fa9e
            client-secret: Po26uTPGWriIF9fl7wKPVZYRWsVg1EfW
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
            - profile_nickname
            - account_email
            client-name: kakao
            client-authentication-method: POST
            
            
          naver:
            client-id: dbdfDOxkjdI2T0VaudOR
            client-secret: _5BeFt5Mb2
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
            
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id    
            
         
            
                

    
      
  datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    #url: jdbc:oracle:thin:@192.168.0.235:1521:XE
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.235:1521:XE
    #url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: icia
    password: 1234
    


  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  mapper-locations:
  - mappers/*.xml
  
  
  

  

